# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: check-added-large-files


- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    entry: pflake8
    additional_dependencies: [pyproject-flake8]

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    files: \.(py|sh|bat|rst|yml|yaml|md)$
    # args: ["--ignore-words-list", ...]

# - repo: https://github.com/RobertCraigie/pyright-python
#   rev: v1.1.359
#   hooks:
#   - id: pyright

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort (python)
